project:
  type: book
  output-dir: _book

book:
  title: "EuBIC-MS Textbook"
  author: "EuBIC-MS"
  chapters:
    - index.qmd
    - guidelines.qmd
    - introduction.qmd
    - data-preprocessing.qmd
    - identification-search.qmd
    - quantification.qmd
    - post-quantification-processing.qmd
    - significance-analysis.qmd
    - machine-learning-ai.qmd
    - workflows-reproducibility.qmd
    - programming-tools.qmd
    - format-usability-preferences.qmd
    - glossary.qmd
    - authors.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt
